version: 0.2

phases:
  install:
    commands:
      - echo "Upgrading AWScli"
      - echo "Upgrading SAM cli"
      - sam --version
      - aws s3 mb s3://21-aws-lambda-sam-s3-uploader

  build:
    commands:
      - echo "creating Package file for deployment"
      - aws cloudformation package --s3-bucket 21-aws-lambda-sam-s3-uploader --template-file template.yml --output-template-file template-generated.yml

  post_build:
    commands:
      - echo "deploy the serverless app"
      - aws cloudformation deploy --template-file template-generated.yml --stack-name project02 --capabilities CAPABILITY_IAM
